# Helix Config

theme = "tokyonight_moon"

[editor]
#line-number = "relative"
true-color = true

# [editor.whitespace]
# render = "trailing"  

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎"

[editor.gutters.line-numbers]
min-width = 3

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.insert]
S-tab = "move_parent_node_start"
C-g = "normal_mode"
C-p = "move_line_up"
C-n = "move_line_down"

[keys.normal]
tab = "move_parent_node_end"
S-tab = "move_parent_node_start"

[keys.select]
tab = "extend_parent_node_end"
S-tab = "extend_parent_node_start"
y = [":clipboard-yank", "yank"]
